version: '2'
services:
    app_admin:
      container_name: aicall_admin
      image: vue/cli
      build:
        context: .
      ports:
          - "9093:8080"
          - "9094:8000"
          - "9095:8081"
      volumes:
        - ./vuejs_project/:/vuejs_project
        - ~/.aws/:/root/.aws/
      working_dir: /vuejs_project/customer_viewer
      command: vue ui -H 0.0.0.0 -D
